### ISSUE TITLE
Version 4 pinning

### ISSUE THREAD

**Issue by henryiii** [conda-forge/gfortran_impl_osx-64-feedstock#9] opened 2019-02-07 09:50 UTC
The recent update to version 4 broke conda-forge numpy on macos. The following now fails:

```bash
conda create -n numpytest numpy -c conda-forge
conda activate numpytest
python -C "import numpy"
```

Numpy -> blas is looking for `libgfortran.3.dylib`, but `libgfortran.4.dylib` is the only one provided.

**Comment by beckermr** [comment] 2019-02-07 11:54
This should have been patched in the repo data. Looks like that did not happen. Pinging @conda-forge/core for guidance.

**Comment by scopatz** [comment] 2019-02-07 14:47
Maybe we should move the current version of the package to the broken label to get everthing working again.  Then we can worry about the pins

**Comment by beckermr** [comment] 2019-02-07 14:50
Sure. Do you understand why the repo data patches have not propagated?

**Comment by chrisburr** [comment] 2019-02-07 14:51
I think [`gfortran_impl_osx-64`](https://anaconda.org/conda-forge/gfortran_impl_osx-64/files) should also be moved to broken while the pins are fixed.

**Comment by beckermr** [comment] 2019-02-07 14:51
The conda forge pinning repo is fine iiuic

**Comment by scopatz** [comment] 2019-02-07 14:51
I do not.

**Comment by beckermr** [comment] 2019-02-07 14:53
We put the right hotfix in here https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/7

I don’t understand

**Comment by beckermr** [comment] 2019-02-07 14:53
Agreed we have to mark both packages as broken @Chrisburr

**Comment by scopatz** [comment] 2019-02-07 14:54
I have moved the package to broken temporarily. I think pinning might need to be fixed.

**Comment by beckermr** [comment] 2019-02-07 14:55
Thanks @scopatz. Do you know how I can test the repo data patches or is this something @conda-forge/core needs to do?

**Comment by scopatz** [comment] 2019-02-07 14:58
I am not really sure.  I think the main thing here might be that it is an ABI change and so everything that depends on this new package will need to be rebuilt.  

Alternatively, if this is ABI backwards compatible, you can probably just "fake it" by soft-linking `ibgfortran.3.dylib` to point to `libgfortran.4.dylib` in the `build.sh`

**Comment by jjhelmus** [comment] 2019-02-07 15:00
libgfortran.3.dylib and libgfortran.4.dylib are NOT ABI compatible.  Symbols were removing and/or renamed between the two versions.

**Comment by scopatz** [comment] 2019-02-07 15:01
So don't fake it :wink::

**Comment by beckermr** [comment] 2019-02-07 15:01
We have to do the rebuild clearly. I am wondering why the hotfixes we pushed in this https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/7 have not taken effect. @minrk do you know how this works?

**Comment by jjhelmus** [comment] 2019-02-07 15:03
The hotfixes look to be correct but are not showing up in the repodata from anaconda.org.  I'm looking into why this might be on the Anaconda.org side.

**Comment by minrk** [comment] 2019-02-07 15:05
As I understand, hotfixes are applied automatically and periodically, but not instantly. So it could take a moment to occur, but shouldn't require manual intervention after merging the PR.

**Comment by minrk** [comment] 2019-02-07 15:29
btw, is the hotfix applying only to the latest builds of given packages, or all builds? I see, for instance, that the latest mpich build has the right `libgfortran>=3.0.1,<4.0.0a0`, but older builds don't.  Of course, the result was that `conda install fenics` just picked libgfortran 4 and an old build of mpich that lacked the stricter pinning.

**Comment by jjhelmus** [comment] 2019-02-07 16:06
There was a configuration issue where non-patches repodata may have been provided in certain cases which has been fixed on Anaconda.org.  The patched repodata should now be provided in all cases.  It may be necessary to clear the local repodata cache using `conda clean -i`.

This can be confirmed with the following:
```
~$ conda search --info arpack[version=3.6.1,subdir=osx-64,channel=conda-forge]
Loading channels: done
arpack 3.6.1 blas_openblas_0
----------------------------
file name   : arpack-3.6.1-blas_openblas_0.tar.bz2
name        : arpack
version     : 3.6.1
build       : blas_openblas_0
build number: 0
size        : 182 KB
license     : BSD 3-Clause
subdir      : osx-64
url         : https://conda.anaconda.org/conda-forge/osx-64/arpack-3.6.1-blas_openblas_0.tar.bz2
md5         : 3de4b84f564490ab19c99019ed9a5daa
timestamp   : 2018-06-25 09:26:59 UTC
dependencies: 
  - blas 1.1 openblas
  - libgfortran >=3.0.1,<4.0.0.a0
  - openblas 0.2.20|0.2.20.*
```

I had a look at the `patch_instructions.json` file in the latest release of [conda-forge-repodata-patches](https://anaconda.org/conda-forge/conda-forge-repodata-patches).  It does not contain patch instructions for mpich on osx-64.

**Comment by beckermr** [comment] 2019-02-07 16:53
Thanks @jjhelmus. Newer builds of FORTRAN dependent packages should have the correct pinnings put in without any patches assuming they pulled the latest build of gfortran 4.8.5

@scopatz should we remove the broken labels on the neeere gfortran builds?

**Comment by isuruf** [comment] 2019-02-07 17:03
numpy is not patched. Something is wrong with the logic in the script in repodata-patches

**Comment by beckermr** [comment] 2019-02-07 17:27
Good catch @isuruf! I’ll look into this and file a bug fix.

**Comment by beckermr** [comment] 2019-02-07 17:27
Also good luck with the studying! :)

**Comment by beckermr** [comment] 2019-02-07 17:34
I've made an issue to track this here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/10

**Comment by beckermr** [comment] 2019-02-11 20:11
This is now fixed! 

```
numpy 1.15.1 py37_blas_openblashd3ea46f_1
-----------------------------------------
file name   : numpy-1.15.1-py37_blas_openblashd3ea46f_1.tar.bz2
name        : numpy
version     : 1.15.1
build       : py37_blas_openblashd3ea46f_1
build number: 1
size        : 4.0 MB
license     : BSD 3-Clause
subdir      : osx-64
url         : https://conda.anaconda.org/conda-forge/osx-64/numpy-1.15.1-py37_blas_openblashd3ea46f_1.tar.bz2
md5         : 85eae7c9406adf67118eb756cfca85ef
timestamp   : 2018-09-03 16:37:37 UTC
dependencies: 
  - blas 1.1 openblas
  - libgfortran >=3.0.1,<4.0.0.a0
  - openblas >=0.2.20,<0.2.21.0a0
  - python >=3.7,<3.8.0a0
```

**Closed as completed** 2019-02-11 20:11 UTC

**Comment by sgsokol** [comment] 2019-12-20 16:49
Hi,
I am new to conda-forge submission and I fell in a similar issue but this time with an R package.
I'm trying to submit PR for r-rmumps package https://github.com/conda-forge/staged-recipes/pull/10470
An example of CI check log on osx-64 can be seen here:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/105165/logs/29

The error message says:
```
2019-12-20T15:30:27.1189450Z dyld: Library not loaded: @rpath/libgfortran.3.dylib
2019-12-20T15:30:27.1193360Z   Referenced from: /usr/local/miniconda/conda-bld/r-rmumps_1576855684878/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/R/lib/libRblas.dylib
2019-12-20T15:30:27.1194750Z   Reason: image not found
```
As you can see it is libgfortran.3.dylib which is referenced in libRblas.dylib while it is v4 which is installed with r-base-3.5.1:
```
2019-12-20T15:28:04.4878660Z Resolved dependencies, will be built in the following order:
2019-12-20T15:28:04.4880270Z     r-rmumps-5.2.1_7-r_base_3.5.1-on-osx-64
2019-12-20T15:28:04.4881460Z     r-rmumps-5.2.1_7-r_base_3.6-on-osx-64
...
2019-12-20T15:29:15.1089190Z   environment location: /usr/local/miniconda/conda-bld/r-rmumps_1576855684878/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
2019-12-20T15:29:15.1089840Z 
2019-12-20T15:29:15.1103770Z 
2019-12-20T15:29:15.1104830Z The following NEW packages will be INSTALLED:
...
2019-12-20T15:29:15.1143010Z     libgfortran:          4.0.0-2                    conda-forge
...
2019-12-20T15:29:15.1157040Z     r-base:               3.5.1-h539fb6c_1           defaults   

```
By the way, it is also libgfortran.3.dylib which is mentioned in build.sh generated by skeleton cran and more recent conda_r_skeleton_helper. Maybe these two should be updated too to integrate v4.

Anybody can help?
Thanks in advance.

**Comment by beckermr** [comment] 2019-12-20 17:08
This is a linking issue I think. Best to address it on one of the repos above.

**Comment by isuruf** [comment] 2019-12-20 22:17
This is an issue with the `r-base` package from defaults. I'm not sure why the defaults package is getting picked up.

**Comment by beckermr** [comment] 2019-12-20 22:37
Conda just pushed 4.8. I’ve seen a few other solver failures. I wonder if there is a bug.
